### ISSUE TITLE
Stringer Deobfuscation

### ISSUE THREAD

**Issue by FFY00** [c001man/deobfuscator#1]
Did you had any success in deobfuscation stringer? I keep getting that 'Could not find invoker' error. Do you know what is causing this? I haven't really looked to the code enough time to understand the error. Maybe I can help.

**Comment by c001man** [comment]
Make sure your sample contained stringer obfuscation only.
Or probably the old string decryptor fault.
It is not a rigorous enough to check the stringer methods.

**Comment by FireMasterK** [comment]
Stringer deobfuscation works perfectly.

**Comment by c001man** [comment]
Try the last commit. Reopen this issue if the problem still appears.

**Comment by FFY00** [comment]
It's working now. Do you have any idea when you will implement obfuscated calls deobfuscation (also by Stringer). I want to help, how can I contact you?

**Comment by Janmm14** [comment]
Best would be to delete this project. kthx
